fix(core): Fixed PageLoader.load() missing return type
This causes `error TS7010: 'load', which lacks return-type annotation, implicitly has an 'any' return type` when `noImplicitAny` is enabled.